# -*- coding: utf-8 -*-
"""prog_avanzada_tp_integ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwgGSByV-Nzu6ctOsxDGELsYr7LGlv-A
"""

import random
import numpy as np

class N_Reinas():

  def cromosoma(self):
    #Comenzar con una población inicial, la cual puede ser generada de manera aleatoria
    #se genera un array que representa la ubicacion de la reina en el tablero nxn.
    pass

  def __init__(self, n, cant_poblacion):
    #constructor de clase N_Reinas
    self.dimension= n
    self.cant_poblacion= cant_poblacion
    pass

  def fitness(self):
    #metodo de la clase N_Reinas quepermite valorar la aptitud de los individuos, dando una puntuación en términos de porcentaje
    #min_ataques=0, max_ataques=n.(n-1)/2
    ## Restricción 1: Evitar que haya mas de una reina por columna, esto se logra por la forma de representación de las reinas en el array. 
    ## Restricción 2: Evitar que haya mas de una reina por fila, la restricción, R_i≠R_J (filas) garantiza valores distintos para las filas.
    ## Restricción 3: Evitar que haya mas de una reinas en posición de ataque por diagonales, 
    #  la restricción R_i+i≠R_J+j (diagonal 1), evita posiciones en las diagonales derecha-arriba hacia izquierda-abajo
    #  y la restricción R_i-i≠R_J-j (diagonal 2), evita posiciones en las diagonales izquierda-arriba hacia derecha-abajo.
    pass

  def seleccion(self):
    #método de la clase N_Reinas que al aplicar el operador de selección con base en el fitness de la población, se seleccionan aquellos cromosomas que tengan más oportunidad de seguir, 
    #o sea aquellos que tienen el fitness más alto.
    pass

  def cruza(self):
    #método de la clase N_Reinas dondese seleccionan al azar dos cromosomas (individuos) padres y un punto de fraccionamiento también al azar 
    #y se obtienen dos hijos permutando los fragmentos de ambos padres.
    pass

  def mutacion(self):
    #método de la clase N_Reinas que proporciona un pequeño elemento de aleatoriedad en los individuos de la población, cambia uno o más genes del cromosoma.
    pass

  def aceptacion(self):
    #método de la clase N_Reinas donde se acepta o evalua la aceptacion.
    pass

  def sustitucion(self):
    #método de la clase N_Reinas
    pass

  def test(self):
    pass 

  def mostrar_tablero(self):
    #método de la clase N_Reinas
    pass